# Generated by Django 4.0.2 on 2022-02-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogidentify',
            name='dog_pic',
            field=models.ImageField(upload_to='dog_img'),
        ),
    ]
